### ISSUE TITLE
HathiTrust record is unviewable

### ISSUE THREAD

**Issue by meunierd** [standardebooks/yevgeny-zamyatin_we_gregory-zilboorg#1]
There don't actually appear to be any scans underlying this production. The HathiTrust record is search-only. This production seems to be riddled with punctuation errors but I'm unable to locate any scans to compare against.

**Comment by acabal** [comment]
I'm able to see the full page scans. HathiTrust probably restricts non-US IP addresses. If you're able to make corrections then please open a pull request. Thanks!
